spring.application.name=auth-service
server.port=9000

# Helpful in logs + issuer construction in real deployments
# (For Postman learning, defaults are fine; you can set issuer explicitly later if needed.)
# spring.security.oauth2.authorizationserver.issuer=http://localhost:9000

logging.level.org.springframework.security=INFO
